# File: templates/azp/hassio-addons/steps/azp-beta-config-changer.yml

steps:
  - script: |
      release="$(Build.SourceBranchName)"
      if [[ "$release" =~ b ]] && [[ -n $(gitAddonBeta) ]]; then
        $version="$(jq --raw-output '.version' config.json)"
        $image="$(jq --raw-output '.image' config.json)"
        sed -i "s|$version|$release|g" config.json
        sed -i "s|$image|${image}-image|g" config.json
      fi
    displayName: 'Update config.json if beta version'

