parameters:
  addon: ''

jobs:
- job: 'Build ${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        jq curl
      release="$(Build.SourceBranchName)"