# Template for hassio-addons.

parameters:
  addon: ''
  arch: ''

jobs:
- job: 'build_${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 360
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerToken)
    displayName: 'Docker Hub Login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Hass.io Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --addon ${{ parameters.arch }} -t /data \
        --docker-hub $(dockerRepo) --docker-hub-check
    displayName: 'Building ${{ parameters.addon }}'