parameters:
  addon: ''
  arch: ''
  repo: ''

stages:
- stage: Build
  jobs: 
  - template: jobs/azp-build-addon.yml
    parameters:
      addon: '${{ parameters.addon }}'
      arch: '${{ parameters.arch }}'
- stage: Publish
  jobs: 
  - template: jobs/azp-publish-addon.yml
    parameters:
      addon: '${{ parameters.addon }}'
      repo: '${{ parameters.repo }}'