parameters:
  addon: ''
  repo: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        git jq curl
      git config --global user.name "$(gitUserName)"
      git config --global user.email "$(gitUserEmail)"
      git config --global credential.helper store
      echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
    displayName: 'Install requirements'
  - script: |
      release="$(Build.SourceBranchName)"
      if [[ "$release" =~ b ]]; then
        git clone $(gitAddonBeta)
      else
        git clone $(gitAddonRepoShort)
      fi
      cd '$(gitAddonRepoShort)/${{ parameters.addon }}'
      cp ../../config.json config.json
      if [ -f ../../icon.png ]; then
        cp ../../icon.png icon.png
      fi
      if [ -f ../../logo.png ]; then
        cp ../../icon.png logo.png
      fi
      if [ -f ../../README.md ]; then
        cp ../../README.md README.md
      fi
      if [ -f ../../CHANGELOG.md ]; then
        cp ../../CHANGELOG.md CHANGELOG.md
      fi
      if [[ "$release" =~ b ]]; then
        $version="$(jq --raw-output '.version' config.json)"
        $image="$(jq --raw-output '.image' config.json)"
        sed -i "s|$version|$release|g" config.json
        sed -i "s|$image|${image}-image|g" config.json
      fi
      git commit -am "Bump ${{ parameters.addon }} version"
      git push
    displayName: 'Update repository $(gitAddonRepoShort)'