# File: templates/azp/hassio-addons/jobs/azp-publish-addon.yml

parameters:
  addon: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        git jq curl
      git config --global user.name "$(gitUserName)"
      git config --global user.email "$(gitUserEmail)"
      git config --global credential.helper store
      echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
    displayName: 'Install requirements'
  - template: ../steps/azp-beta-addon.yml
  - script: |
      release="$(Build.SourceBranchName)"
      repo="$(gitAddonRepo)"
      oDir=pwd
      echo "$oDir"
      function copy_files () {
        cd ../
        git clone $repoUrl
        mkdir -p "$repo/${{ parameters.addon }}"
        cd "$repo/${{ parameters.addon }}"
        echo "  Copying config.json"
        cp $oDir/config.json config.json
        if [ -f $oDir/icon.png ]; then
          echo "  Copying icon.png"
          cp $oDir/icon.png icon.png
        fi
        if [ -f $oDir/logo.png ]; then
          echo "  Copying logo.png"
          cp $oDir/icon.png logo.png
        fi
        if [ -f $oDir/README.md ]; then
          echo "  Copying README.md"
          cp $oDir/README.md README.md
        fi
        if [ -f $oDir/CHANGELOG.md ]; then
          echo "  Copying CHANGELOG.md"
          cp $oDir/CHANGELOG.md CHANGELOG.md
        fi
        git add --all
        git commit -am "Bump ${{ parameters.addon }} version"
        git push origin master
        cd $oDir
      }
      repoUrl="https://github.com/$(gitUser)/$(gitAddonRepo)"
      if [[ "$release" =~ b ]] && [[ -n $(gitAddonRepoBeta) ]]; then
        repoUrl="https://github.com/$(gitUser)/$(gitAddonRepoBeta)"
        repo=$(gitAddonRepoBeta)
        copy_files
      elif [[ -n $(gitAddonRepoBeta) ]]; then
        copy_files
        repoUrl="https://github.com/$(gitUser)/$(gitAddonRepoBeta)"
        repo=$(gitAddonRepoBeta)
        copy_files
      else
        copy_files
      fi
    displayName: 'Copy required files'

