# File: templates/azp/hassio-addons/jobs/azp-validate-addons.yml

parameters:
  addon: ''
  repo: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        jq curl
    displayName: 'Install requirements'
  - script: |
      release="$(Build.SourceBranchName)"
      config_version="$(jq --raw-output '.version' config.json)"
      if [[ $release == $config_version ]]; then
        echo config.json version validated!
        exit 0
      elif [[ $release =~ b ]]; then
        echo Building for beta version
        exit 0
      else
        echo "Config version has not been updated or is incorrect!"
        exit 1
      fi
    displayName: 'Check config.json version'