# File: templates/azp/hassio-addons/jobs/azp-publish-addon.yml

parameters:
  addon: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        git jq curl
      git config --global user.name "$(gitUserName)"
      git config --global user.email "$(gitUserEmail)"
      git config --global credential.helper store
      echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
    displayName: 'Install requirements'
  - template: ../steps/azp-beta-addon.yml
  - script: |
      release="$(Build.SourceBranchName)"
      repo="$(gitAddonRepo)"
      repoUrl="https://github.com/$(gitUser)/$(gitAddonRepo)"
      if [[ "$release" =~ b ]] && [[ -n $(gitAddonRepoBeta) ]]; then
        repoUrl="https://github.com/$(gitUser)/$(gitAddonRepoBeta)"
        repo=$(gitAddonRepoBeta)
      fi
      
      git clone $repoUrl
      mkdir -p "$repo/${{ parameters.addon }}"
      cd "$repo/${{ parameters.addon }}"
      echo "Copying config.json"
      cp ../../config.json config.json
      if [ -f ../../icon.png ]; then
        echo "Copying icon.png"
        cp ../../icon.png icon.png
      fi
      if [ -f ../../logo.png ]; then
        echo "Copying logo.png"
        cp ../../icon.png logo.png
      fi
      if [ -f ../../README.md ]; then
        echo "Copying README.md"
        cp ../../README.md README.md
      fi
      if [ -f ../../CHANGELOG.md ]; then
        echo "Copying CHANGELOG.md"
        cp ../../CHANGELOG.md CHANGELOG.md
      fi
      cd ../..
      mv $repo/ ../$repo/
      cd ../$repo
      git add --all
      git commit -am "Bump ${{ parameters.addon }} version"
      git push origin master
    displayName: 'Copy required files'

