# File: templates/azp/hassio-addons/jobs/azp-publish-addon.yml

parameters:
  addon: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        git jq curl
      git config --global user.name "$(gitUserName)"
      git config --global user.email "$(gitUserEmail)"
      git config --global credential.helper store
      echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
    displayName: 'Install requirements'
  - template: ../steps/azp-version-addon.yml
  - script: |
      release="$(Build.SourceBranchName)"
      repo="$(gitAddonRepoShort)"
      repoUrl="https://github.com/$(gitUser)/$(gitAddonRepo)"
      if [[ "$release" =~ b ]] && [[ -n $(gitAddonRepoBeta) ]]; then
        repoUrl="https://github.com/$(gitUser)/$(gitAddonRepoBeta)""
        repo=$(gitAddonRepoBeta)
      fi
      git clone $repoUrl
      mkdir -p '$repo/${{ parameters.addon }}'
      cd '$repo/${{ parameters.addon }}'
      cp ../../config.json config.json
      if [ -f ../../icon.png ]; then
        cp ../../icon.png icon.png
      fi
      if [ -f ../../logo.png ]; then
        cp ../../icon.png logo.png
      fi
      if [ -f ../../README.md ]; then
        cp ../../README.md README.md
      fi
      if [ -f ../../CHANGELOG.md ]; then
        cp ../../CHANGELOG.md CHANGELOG.md
      fi
      git commit -am "Bump ${{ parameters.addon }} version"
      git push
    displayName: 'Copy required files'

