# File: templates/azp/hassio-addons/jobs/azp-publish-addon.yml

parameters:
  addon: ''
  repo: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        git jq curl
      git config --global user.name "$(gitUserName)"
      git config --global user.email "$(gitUserEmail)"
      git config --global credential.helper store
      echo "https://$(githubToken):x-oauth-basic@github.com" > $HOME/.git-credentials
    displayName: 'Install requirements'
  - script: |
      release="$(Build.SourceBranchName)"
      if [[ "$release" =~ b ]] && [[ -n $(gitAddonBeta) ]]; then
        git clone $(gitAddonBeta)
      else
        git clone $(gitAddonRepoShort)
      fi
      mkdir -p '$(gitAddonRepoShort)/${{ parameters.addon }}'
      cd '$(gitAddonRepoShort)/${{ parameters.addon }}'
      cp ../../config.json config.json
      if [ -f ../../icon.png ]; then
        cp ../../icon.png icon.png
      fi
      if [ -f ../../logo.png ]; then
        cp ../../icon.png logo.png
      fi
      if [ -f ../../README.md ]; then
        cp ../../README.md README.md
      fi
      if [ -f ../../CHANGELOG.md ]; then
        cp ../../CHANGELOG.md CHANGELOG.md
      fi
    displayName: 'Copy required files to repo $(gitAddonRepoShort)'
  - template: ../steps/azp-beta-config-changer.yml
  - script: |
      git add --all
      git commit -am "Bump ${{ parameters.addon }} version"
      git push origin master
    displayName: "Commit and push changes"
