parameters:
  addon: ''
  repo: ''

jobs:
- job: '${{ parameters.addon }}'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get install -y --no-install-recommends \
        jq curl
    dipsplayName: 'Install requirements'
  - script: |
      release="$(Build.SourceBranchName)"
      config_version="$(jq --raw-output '.version' config.json)"

      if [[ $release != $config_version ]]; then
        echo "Config version has not been updated!"
        exit 1
      fi
    displayName: 'Check config.json version'